services:
  autenticacao:
    build: ./microservico-autenticacao
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=aps-map-p2-jwt-secret-key-minimo-32-caracteres

  academico:
    build: ./microservico-academico
    ports:
      - "8082:8082"
    environment:
      - JWT_SECRET=aps-map-p2-jwt-secret-key-minimo-32-caracteres
      - AUTH_SERVICE_URL=http://autenticacao:8081
    depends_on:
      - autenticacao
