server:
  port: 8082

spring:
  application:
    name: microservico-academico
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5433/academicdb}
    username: ${SPRING_DATASOURCE_USERNAME:aps}
    password: ${SPRING_DATASOURCE_PASSWORD:aps123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:aps-map-p2-jwt-secret-key-minimo-32-caracteres}

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
