server:
  port: 8081

spring:
  application:
    name: microservico-autenticacao
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:aps-map-p2-jwt-secret-key-minimo-32-caracteres}
  expiration-ms: 86400000
